CUDA_VISIBLE_DEVICES=6,7 torchrun --standalone --nnodes 1 --nproc-per-node 2 vla-scripts/finetune.py \
  --vla_path /nvmessd/ssd_share/tengbo/openvla-oft/model \
  --data_root_dir /nvmessd/ssd_share/tengbo/openvla-oft/data \
  --dataset_name libero_spatial_no_noops \
  --run_root_dir /nvmessd/ssd_share/tengbo/openvla-oft/log \
  --use_l1_regression True \
  --use_diffusion False \
  --use_film False \
  --num_images_in_input 2 \
  --use_proprio True \
  --batch_size 4 \
  --learning_rate 5e-4 \
  --num_steps_before_decay 100000 \
  --max_steps 150005 \
  --save_freq 10000 \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --lora_rank 32 \
  --wandb_entity tengboyu1 \
  --wandb_project OFT-vla-finetune \
  --run_id_note parallel_dec--8_acts_chunk--continuous_acts--L1_regression--3rd_person_img--wrist_img--proprio_state